# Generated by Django 5.2.8 on 2025-11-22 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='content',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 12, 0, 33, 582210)),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 12, 0, 33, 582242)),
        ),
        migrations.AddField(
            model_name='collector',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 12, 0, 33, 583181)),
        ),
    ]
