# Generated by Django 5.2.8 on 2025-11-22 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apitoken_content_apitoken_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 11, 22, 15, 8, 49, 454394))),
            ],
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 15, 8, 49, 452696)),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 15, 8, 49, 452730)),
        ),
        migrations.AlterField(
            model_name='collector',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 15, 8, 49, 453570)),
        ),
    ]
