# Generated by Django 5.2.8 on 2025-11-22 15:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_log_alter_apitoken_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='message',
        ),
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='log',
            name='collector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.collector'),
        ),
        migrations.AddField(
            model_name='log',
            name='raw_content',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 16, 17, 21, 839672)),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 16, 17, 21, 839704)),
        ),
        migrations.AlterField(
            model_name='collector',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 16, 17, 21, 840425)),
        ),
    ]
